.TH USYNC 1 "2024-11-25" "usync" "Usync Manual"
.SH NAME
usync \- push/pull changes from remote host
.SH SYNOPSIS
\fBusync\fR <\fIcommand\fR> [\fIoption\fR...]
.SH DESCRIPTION
\fBusync\fR is an rsync wrapper configured by a basic yaml file. \fBusync\fR
searches the current and parent directories for a file named \fI.usync\fR. The
directory containing \fI.usync\fR is the local base working directory while the
contents of \fI.usync\fR define a remote rsync host.
.P
\fBusync\fR forms an rsync command to push/pull the contents of the base
working directory to/from the remote host using the rsync options: \fB-azz
--delete --protect-args\fR. Exclude patterns may be added in \fI.usync\fR or
via command line arguments.
.SH COMMANDS
.TP
\fBinit\fR
Create a new \fI.usync\fR file in current directory.
.TP
\fBpush\fR
Push changes to remote rsync host.
.TP
\fBpull\fR
Pull changes from remote rsync host.
.SH OPTIONS
.TP
\fB\-c\fR, \fB\-\-config\fR <\fIfile\fR>
Set config file basename. (default: \fI.usync\fR)
.TP
\fB\-d\fR, \fB\-\-dir\fR <\fIdirectory\fR>
Set remote rsync directory.
.TP
\fB\-e\fR, \fB\-\-exclude\fR <\fIpattern\fR>
Add to rsync exclude patterns.
.TP
\fB\-p\fR, \fB\-\-port\fR <\fIport\fR>
Set remote rsync port number.
.TP
\fB\-r\fR, \fB\-\-remote\fR, \fB\-\-url\fR <\fIport\fR>
Set remote rsync url. May be an ssh alias.
.TP
\fB\-u\fR, \fB\-\-user\fR <\fIport\fR>
Set remote rsync user.
.TP
\fB\-D\fR, \fB\-\-dryrun\fR
Perform dry run making no changes.
.TP
\fB\-Q\fR, \fB\-\-quiet\fR
Don't write anything to stdout.
.TP
\fB\-V\fR, \fB\-\-verbose\fR
Print more verbose information.
.TP
\fB\-\-nocolor\fR
Disable colored output.
.TP
\fB\-H\fR, \fB\-\-help\fR
Print help text.
.SH CONFIG
\fBusync\fR is configured by a yaml file \fI.usync\fR that defines a remote
rsync host and directory. This file must be present to \fBpush\fR or \fBpull\fR
from a remote host.
.P
\fI.usync\fR has the following keys:
.TP
\fBdir\fR
Remote rsync directory. Must be a full path. (required)
.TP
\fBremote\fR or \fBurl\fR
Remote rsync url. May be an ssh alias. (required)
.TP
\fBport\fR
Remote ssh port.
.TP
\fBuser\fR
Remote ssh user.
.TP
\fBexclude\fR
List of patterns to exclude via rsync \fB--exclude\fR option. See \fBFILTER
RULES\fR section of rsync manual for details and syntax. (optional)
.SH ENVIRONMENT
\fBusync\fR is affected by the following environment variables:
.TP
\fBNOCOLOR\fR=1
Disable colored output.
.TP
\fBQUIET\fR=1
Run silently.
.TP
\fBVERBOSE\fR=1
Run verbosely.
.SH REQUIREMENTS
\fBrsync\fR and \fBssh\fR
.SH AUTHOR
Chris Magyar
